import type { Metadata } from "next";
import "./globals.css";
import { montserrat } from "./fonts/fonts";
import { cn } from "@/lib/utils";
import Logo from "@/components/logo";
import HeaderNavbar from "@/components/header-navbar";
import FooterSection from "@/components/footer/footer-section";

export const metadata: Metadata = {
  title: "Yash Gupta",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "bg-[#07071a] text-white",
          montserrat.className,
        )}
      >
        <header className="sticky top-0 z-50 animate-slideDown border-b border-white/6 bg-[#07071a]/90 backdrop-blur-md">
          <div className="xl:px-40 lg:px-28 sm:px-20 px-4 flex items-center justify-between py-5">
            <Logo />
            <HeaderNavbar />
          </div>
        </header>

        {children}

        <FooterSection />
      </body>
    </html>
  );
}
