import type { Metadata } from "next";
import "./globals.css";
import { montserrat } from "./fonts/fonts";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "bg-linear-to-br from-[#150e33] via-[#0d091f] to-black text-white",
          montserrat.className,
        )}
      >
        {children}
      </body>
    </html>
  );
}
